config/routes.rb
Rails.application.routes.draw do
  get 'thots/index'
  get 'thots/category'
  get 'thots/categories'
  get 'thots/destroy'

  root 'thots#index'

  namespace :api do
    get 'thots/:id' => 'thots#show'
    post 'thots/create' => 'thots#create'
    get 'search' => 'thots#search'
  end

  resources :thots, only: [:new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/thot.rb
class Thot < ActiveRecord::Base
  belongs_to :parent, class_name: "Thot"
  has_many :thots, foreign_key: "parent_id"

  def self.search(search)
    search_results = where("title || details LIKE ?", "%#{search}%")
    filter_child_results(search_results)
  end

  private

  def self.filter_child_results(query)
    query.where(parent_id: nil)
  end
end

app/controllers/api/thots_controller.rb
# TODO: Namespace for Internal Api
# TODO: Create Thot Presenter
class Api::ThotsController < ApplicationController
  def create
    Thot.create!(title: params[:title],
                 details: params[:details],
                 parent_id: params[:parent_id])

    #I know this is a lazy way to re-render the ThotWindow after an update of adding
    #a new response, but whatever let's just finish this.
    parent_thot = Thot.find(params[:parent_id])
    render json: {
        thot: parent_thot,
        relatedThots: related_thots_json_array(parent_thot)
    }.to_json
  end

  def show
    thot = Thot.find(params[:id])
    render json: {
      thot: thot,
      relatedThots: related_thots_json_array(thot)
    }.to_json
  end

  def search
    thot_results = Thot.search(params[:keyword])
    render json: {
      results: thot_results
    }
  end

  private

  def related_thots_json_array(thot)
    related_thots = []
    thot.thots.each do |currentThot|
      thot_json = {
        id: currentThot.id,
        title: currentThot.title,
        details: currentThot.details
      }
      related_thots << thot_json
    end

    related_thots
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thots_controller.rb
class ThotsController < ApplicationController
  def index
  end

  def new
  end

  def create
    category_param = params[:category]
    category = Category.find_by(title: category_param)

    if category.nil?
      category = Category.create!(
          title: category_param,
          url_friendly_title: category_param.gsub(' ', '_').underscore
      )
    end

    @created_thot = Thot.create!(
        title: params[:title],
        details: params[:details],
        category_id: category.id,
        parent_id: params[:parent_id]
    )

    redirect_to thots_category_path(category_title: Category.find(category.id).url_friendly_title)
  end

  def category
    category_id = Category.find_by(url_friendly_title: params[:category_title]).id
    @thots = Thot.where(category_id: category_id)
  end

  def categories
    @categories = Category.all
  end

  def destroy
    @thot = Thot.destroy(params[:id])
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thots_helper.rb
module ThotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThotPotv201712</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "/global_header"%>

<div class="main-content">
  <%= yield %>
</div>

</body>
</html>

app/views/thots/categories.html.erb
<h1>Thot#categories</h1>
<p>Find me in app/views/thot/categories.html.erb</p>

<% @categories.each do |category| %>
    <div>
      <%= link_to(category.title, thots_category_path(category_title: category.url_friendly_title)) %>
    </div>
<% end %>

app/views/thots/category.html.erb
<h1>Thot#category</h1>
<p>Find me in app/views/thot/category.html.erb</p>

<% @thots.each do |thot| %>
    <div class=<%= "thot-#{thot.id}" %>>
      <h3><%= "(#{thot.id}) #{thot.title}" %></h3>
      <p><%= thot.details %></p>

      <div>
        <%= link_to "Delete", thots_destroy_path(id: thot.id), class: 'delete-button' %>
      </div>
    </div>
    <br>
    ------------
<% end %>

app/views/thots/create.html.erb
<%= @created_thot.title %>

app/views/thots/index.html.erb
<h1>Explore</h1>

<%= react_component('ThotDashboard') %>

<br>

<div>
  <%= link_to "Create New Thot", new_thot_path, class: 'button' %>
  <%= link_to "Browse Categories", thots_categories_path, class: 'button' %>
</div>

app/views/thots/new.html.erb
<h1>Thot#new</h1>
<p>Find me in app/views/thot/new.html.erb</p>

<%= form_tag("/thots", method: "post") do %>
    <p>
      <%= label_tag(:title, "Title:") %>
      <%= text_field_tag(:title) %>
    </p>

    <p>
      <%= label_tag(:details, "Details:") %>
      <%= text_area_tag(:details) %>
    </p>

    <p>
      <%= label_tag(:category, "Category:") %>
      <%= text_field_tag(:category) %>
    </p>

    <p>
      <%= label_tag(:parent_id, "Parent ID:") %>
      <%= text_field_tag(:parent_id) %>
    </p>

    <%= submit_tag("Create Thot") %>
<% end %>